spring:
  cloud:
    config:
      uri: http://localhost:8001  # Expect the Spring Cloud Config server to be running on localhost, port 8001.  
  datasource:
    password: admin
    username: root
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${PORT:${SERVER_PORT:0}}


  